### PR TITLE
Minor fixes to allow compile with pre-stone age HWLOC

### PR DESCRIPTION
**Pull request by hppritcha**
Enables build against v1.11.8 and above.

### CODE REVIEW

**Comment by jsquyres** [comment]
Is the reason to do this because we want to support v1.11.0, per the Open MPI docs https://docs.open-mpi.org/en/v5.0.x/installing-open-mpi/required-support-libraries.html ?

**Review by jsquyres — APPROVED** [review]

**Comment by hppritcha** [comment]
I guess.  I was just adding what @rhc54 added on upstream, I think because of problems @wenduwan was having on graviton3?

**Comment by rhc54** [comment]
Nothing to do with chip type - problem is that pre-stone age hwloc doesn’t see numa in some chips and we bind to numa by default Sent from my iPhoneOn Jul 11, 2024, at 12:46 PM, Wenduo Wang ***@***.***> wrote:﻿
It's not Graviton in particular. It happens for Intel as well
@hppritcha I think you need to include ***@***.*** as well

**Comment by rhc54** [comment]
Only support v1.11.8 and above Sent from my iPhoneOn Jul 11, 2024, at 12:39 PM, Jeff Squyres ***@***.***> wrote:﻿
Is the reason to do this because we want to support v1.11.0, per the Open MPI docs https://docs.open-mpi.org/en/v5.0.x/installing-open-mpi/required-support-libraries.html ?

**Pull request merged**
