### PR TITLE
MPI 4.1: add support for memory-alloc-kinds

### PR DESCRIPTION
**Pull request by hppritcha**
MPI 4.1: add support for memory-alloc-kinds
Changes will need to be made to Open MPI to parse the contents of
the OMPI_MCA_mpi_memory_alloc_kinds environment variable to
determine how to use the user supplied memory-alloc-kinds information.

See section 11.4.3 of the MPI 4.1 standard.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>
(cherry picked from commit https://github.com/open-mpi/prrte/commit/c5953e13bdc76b4a1f37c6bba1a11b26d557a22b)

### CODE REVIEW

**Comment by janjust** [comment]
Probably need to add CI. At the very least github actions.
And maybe a description about this PR since it was discussed at the dev. meeting?

**Comment by hppritcha** [comment]
i'll open a separate pr to add some of the upstream ci sanity checks then rebase this one.  the description is a little light because its to commits.   I'll fix that up.

**Comment by naughtont3** [comment]
@hppritcha Quick sanity check looked good.  Also, skimmed MPI-4.1 and do not recall how we intended to reflect valid values that can be passed here.  Added complication being that `mpirun --help` just tells us to look at mpirun(1).

**Comment by rhc54** [comment]
FWIW: I found a few in one doc: `system,mpi,rocm:device`. No idea what the complete list looks like - if someone can pass it along, I can add to the help output.

**Review by janjust — APPROVED** [review]

**Pull request merged**
